# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c3d70b6687284bb474255c48649995130805b28972907102b5203c336deac6ae1edeee2a4840e1562382c1c6a21c606b5a5ffc811731b9b5ed5d5a8c1006a35

test:
  secret_key_base: 2789446aab72882df724d3b6870c0703e7d1e32beb9d1dc0063ed7bc40a6cb41cfbb075e04916d76d893c1979850c5050c7dd567d111a7368964e760ea17981d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
